const assert = require('assert');
const vscode = require('vscode');
const path = require('path');
const fs = require('fs');

// Import extension modules for testing
const { generateFileAliases } = require('../../../src/features/updateLuaFileAliases');

// Import shared test utilities
const {
    mockWorkspaceConfig,
    createTestFiles,
    cleanupTestFiles,
    setupTestWorkspace
} = require('../utils/testUtils');

suite('File Alias Generation Tests', () => {
    vscode.window.showInformationMessage('Starting File Alias Generation tests...');

    let testWorkspaceUri;
    let testWorkspacePath;

    suiteSetup(async () => {
        testWorkspaceUri = vscode.Uri.file(path.join(__dirname, 'alias-test-workspace'));
        testWorkspacePath = testWorkspaceUri.fsPath;
        
        if (!fs.existsSync(testWorkspacePath)) {
            fs.mkdirSync(testWorkspacePath, { recursive: true });
        }
        
        await setupTestWorkspace(testWorkspacePath);
    });

    suiteTeardown(async () => {
        if (fs.existsSync(testWorkspacePath)) {
            fs.rmSync(testWorkspacePath, { recursive: true, force: true });
        }
    });

    test('Should generate unique aliases for non-conflicting files', async () => {
        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            manualAliases: {
                '@Server': 'src/Server',
                '@Client': 'src/Client',
                '@Shared': 'src/Shared'
            }
        });

        try {
            generateFileAliases();
            
            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            assert.ok(fs.existsSync(luaurcPath), '.luaurc should exist');
            
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));
            assert.ok(luaurcContent.aliases, 'Aliases should be generated');
            assert.ok(luaurcContent.aliases.ServerMain, 'ServerMain alias should exist');
            assert.ok(luaurcContent.aliases.ClientMain, 'ClientMain alias should exist');
            assert.ok(luaurcContent.aliases.Config, 'Config alias should exist');
            assert.ok(luaurcContent.aliases.Utils, 'Utils alias should exist for init file');
            assert.ok(!luaurcContent.aliases.PrivateFile, 'Private files should be ignored');
            assert.ok(luaurcContent.aliases['@Server'], 'Manual @Server alias should exist');
            assert.ok(luaurcContent.aliases['@Client'], 'Manual @Client alias should exist');
            assert.ok(luaurcContent.aliases['@Shared'], 'Manual @Shared alias should exist');
        } finally {
            restore();
        }
    });

    test('Should handle ambiguous aliases correctly', async () => {
        const duplicateFile = path.join(testWorkspacePath, 'src/Client/Config.luau');
        fs.writeFileSync(duplicateFile, 'local ClientConfig = {}\nreturn ClientConfig');

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client', 'src/Shared'],
            manualAliases: {}
        });

        try {
            generateFileAliases();
            
            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));
            
            const autoGeneratedKeys = Object.keys(luaurcContent.aliases);
            assert.ok(!autoGeneratedKeys.includes('Config'), 'Ambiguous aliases should not be auto-generated');
        } finally {
            restore();
            fs.unlinkSync(duplicateFile);
        }
    });

    test('pathPriority: should resolve ambiguous alias when highest-priority path has a single match', async () => {
        const duplicateFile = path.join(testWorkspacePath, 'src/Client/Config.luau');
        fs.writeFileSync(duplicateFile, 'local ClientConfig = {}\nreturn ClientConfig');

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client', 'src/Shared'],
            manualAliases: {},
            pathPriority: ['src/Client']
        });

        try {
            generateFileAliases();

            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));

            assert.ok(luaurcContent.aliases.Config, 'Config should be resolved by pathPriority');
            assert.strictEqual(luaurcContent.aliases.Config, 'src/Client/Config.luau', 'Config should resolve to the only src/Client match');
        } finally {
            restore();
            fs.unlinkSync(duplicateFile);
        }
    });

    test('pathPriority: should remain ambiguous when highest-priority path has multiple matches', async () => {
        const duplicateFileA = path.join(testWorkspacePath, 'src/Client/Config.luau');
        const duplicateDirB = path.join(testWorkspacePath, 'src/Client/Sub');
        const duplicateFileB = path.join(duplicateDirB, 'Config.luau');
        fs.mkdirSync(duplicateDirB, { recursive: true });
        fs.writeFileSync(duplicateFileA, 'local ClientConfigA = {}\nreturn ClientConfigA');
        fs.writeFileSync(duplicateFileB, 'local ClientConfigB = {}\nreturn ClientConfigB');

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client', 'src/Shared'],
            manualAliases: {},
            pathPriority: ['src/Client', 'src/Shared']
        });

        try {
            generateFileAliases();

            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));

            assert.ok(!luaurcContent.aliases.Config, 'Config should remain ambiguous when highest-priority path ties');
        } finally {
            restore();
            fs.rmSync(path.join(testWorkspacePath, 'src/Client/Sub'), { recursive: true, force: true });
            if (fs.existsSync(duplicateFileA)) {
                fs.unlinkSync(duplicateFileA);
            }
        }
    });

    test('pathPriority: should remain ambiguous when no candidates match any priority path', async () => {
        const duplicateFile = path.join(testWorkspacePath, 'src/Client/Config.luau');
        fs.writeFileSync(duplicateFile, 'local ClientConfig = {}\nreturn ClientConfig');

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client', 'src/Shared'],
            manualAliases: {},
            pathPriority: ['Packages']
        });

        try {
            generateFileAliases();

            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));

            assert.ok(!luaurcContent.aliases.Config, 'Config should remain ambiguous when no pathPriority entries match');
        } finally {
            restore();
            fs.unlinkSync(duplicateFile);
        }
    });

    test('pathPriority: should remain ambiguous when higher priority ties even if lower priority has a unique match', async () => {
        const serverDirA = path.join(testWorkspacePath, 'src/Server/Combat');
        const serverDirB = path.join(testWorkspacePath, 'src/Server/System');
        const clientDir = path.join(testWorkspacePath, 'src/Client');
        const serverFileA = path.join(serverDirA, 'Weapon.luau');
        const serverFileB = path.join(serverDirB, 'Weapon.luau');
        const clientFile = path.join(clientDir, 'Weapon.luau');

        fs.mkdirSync(serverDirA, { recursive: true });
        fs.mkdirSync(serverDirB, { recursive: true });
        fs.mkdirSync(clientDir, { recursive: true });
        fs.writeFileSync(serverFileA, 'local WeaponA = {}\nreturn WeaponA');
        fs.writeFileSync(serverFileB, 'local WeaponB = {}\nreturn WeaponB');
        fs.writeFileSync(clientFile, 'local WeaponClient = {}\nreturn WeaponClient');

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client'],
            manualAliases: {},
            pathPriority: ['src/Server', 'src/Client']
        });

        try {
            generateFileAliases();

            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));

            assert.ok(!luaurcContent.aliases.Weapon, 'Weapon should remain ambiguous because highest-priority path has multiple matches');
        } finally {
            restore();
            cleanupTestFiles(testWorkspacePath, ['src/Server/Combat', 'src/Server/System', 'src/Client/Weapon.luau']);
        }
    });

    test('Should handle files with same basename in different subdirectories', async () => {
        const testDirs = ['src/Server/Combat', 'src/Client/Combat'];
        for (const dir of testDirs) {
            const fullPath = path.join(testWorkspacePath, dir);
            if (!fs.existsSync(fullPath)) {
                fs.mkdirSync(fullPath, { recursive: true });
            }
        }

        const conflictFiles = {
            'src/Server/Combat/Weapon.luau': 'local ServerWeapon = {}\nreturn ServerWeapon',
            'src/Client/Combat/Weapon.luau': 'local ClientWeapon = {}\nreturn ClientWeapon'
        };

        for (const [filePath, content] of Object.entries(conflictFiles)) {
            const fullPath = path.join(testWorkspacePath, filePath);
            fs.writeFileSync(fullPath, content, 'utf8');
        }

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client']
        });

        try {
            generateFileAliases();
            
            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));
            
            assert.ok(!luaurcContent.aliases.Weapon, 'Ambiguous files should not generate aliases');
        } finally {
            restore();
            for (const filePath of Object.keys(conflictFiles)) {
                const fullPath = path.join(testWorkspacePath, filePath);
                if (fs.existsSync(fullPath)) fs.unlinkSync(fullPath);
            }
        }
    });

    test('Should recognize files and folders with init.luau files that share the same name constitute an ambiguous alias', async () => {
        const testDir = path.join(testWorkspacePath, 'src/Shared/TestModule');
        const standaloneFile = path.join(testWorkspacePath, 'src/Shared/TestModule.luau');
        const initFile = path.join(testDir, 'init.luau');

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Shared']
        });

        try {
            // Step 1: Create standalone file only
            fs.writeFileSync(standaloneFile, 'return { standalone = true }');
            generateFileAliases();
            
            let luaurcPath = path.join(testWorkspacePath, '.luaurc');
            let luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));
            
            assert.ok(luaurcContent.aliases.TestModule, 'Step 1: Should create alias when only standalone file exists');
            assert.ok(luaurcContent.aliases.TestModule.includes('TestModule.luau'), 'Step 1: Should point to standalone file');

            // Step 2: Add init file (creates ambiguity)
            fs.mkdirSync(testDir, { recursive: true });
            fs.writeFileSync(initFile, 'return { main = true }');
            generateFileAliases();
            
            luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));
            
            assert.ok(!luaurcContent.aliases.TestModule, 'Step 2: Should NOT create alias when both init file and standalone file exist (ambiguous)');

            // Step 3: Remove init file (removes ambiguity, standalone file should get alias again)
            fs.rmSync(testDir, { recursive: true, force: true });
            generateFileAliases();
            
            luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));
            
            assert.ok(luaurcContent.aliases.TestModule, 'Step 3: Should restore alias when init file removed and only standalone remains');
            assert.ok(luaurcContent.aliases.TestModule.includes('TestModule.luau'), 'Step 3: Should point to standalone file again');

        } finally {
            restore();
            if (fs.existsSync(testDir)) {
                fs.rmSync(testDir, { recursive: true, force: true });
            }
            if (fs.existsSync(standaloneFile)) {
                fs.unlinkSync(standaloneFile);
            }
        }
    });

    test('Should handle files with special characters', () => {
        const specialFiles = {
            'src/Server/File-With-Dashes.luau': 'return {}',
            'src/Server/File_With_Underscores.luau': 'return {}',
            'src/Server/FileWithNumbers123.luau': 'return {}'
        };

        for (const [filePath, content] of Object.entries(specialFiles)) {
            const fullPath = path.join(testWorkspacePath, filePath);
            fs.writeFileSync(fullPath, content, 'utf8');
        }

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server']
        });

        try {
            generateFileAliases();
            
            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));
            
            assert.ok(luaurcContent.aliases['File-With-Dashes'], 'Should handle dashes in filenames');
            assert.ok(luaurcContent.aliases['File_With_Underscores'], 'Should handle underscores in filenames');
            assert.ok(luaurcContent.aliases['FileWithNumbers123'], 'Should handle numbers in filenames');
        } finally {
            restore();
            for (const filePath of Object.keys(specialFiles)) {
                const fullPath = path.join(testWorkspacePath, filePath);
                if (fs.existsSync(fullPath)) fs.unlinkSync(fullPath);
            }
        }
    });

    test('Should ignore .server and .client files', () => {
        const serverClientFiles = {
            'src/Server/ServerScript.server.luau': 'print("server")',
            'src/Client/ClientScript.client.luau': 'print("client")',
            'src/Shared/RegularScript.luau': 'print("regular")'
        };

        for (const [filePath, content] of Object.entries(serverClientFiles)) {
            const fullPath = path.join(testWorkspacePath, filePath);
            fs.writeFileSync(fullPath, content, 'utf8');
        }

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client', 'src/Shared']
        });

        try {
            generateFileAliases();
            
            const luaurcPath = path.join(testWorkspacePath, '.luaurc');
            const luaurcContent = JSON.parse(fs.readFileSync(luaurcPath, 'utf8'));
            
            assert.ok(!luaurcContent.aliases.ServerScript, 'Should ignore .server files');
            assert.ok(!luaurcContent.aliases.ClientScript, 'Should ignore .client files');
            assert.ok(luaurcContent.aliases.RegularScript, 'Should include regular files');
        } finally {
            restore();
            for (const filePath of Object.keys(serverClientFiles)) {
                const fullPath = path.join(testWorkspacePath, filePath);
                if (fs.existsSync(fullPath)) fs.unlinkSync(fullPath);
            }
        }
    });

    // --- ignoreDirectories pattern tests ---

    test('ignoreDirectories: name-only pattern ignores matching directory under any scan root', () => {
        createTestFiles(testWorkspacePath, {
            'src/Server/Ignorable/IgnorableModule.luau': 'return {}',
            'src/Client/Ignorable/AlsoIgnored.luau': 'return {}',
            'src/Server/Visible/VisibleModule.luau': 'return {}'
        });

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client'],
            ignoreDirectories: ['Ignorable']
        });

        try {
            generateFileAliases();

            const luaurcContent = JSON.parse(fs.readFileSync(path.join(testWorkspacePath, '.luaurc'), 'utf8'));
            assert.ok(!luaurcContent.aliases.IgnorableModule, 'Should ignore file under Ignorable in Server');
            assert.ok(!luaurcContent.aliases.AlsoIgnored, 'Should ignore file under Ignorable in Client');
            assert.ok(luaurcContent.aliases.VisibleModule, 'Should include file not under ignored dir');
        } finally {
            restore();
            cleanupTestFiles(testWorkspacePath, [
                'src/Server/Ignorable',
                'src/Client/Ignorable',
                'src/Server/Visible'
            ]);
        }
    });

    test('ignoreDirectories: workspace-relative path pattern ignores only the specific path', () => {
        createTestFiles(testWorkspacePath, {
            'src/Server/Private/SecretA.luau': 'return {}',
            'src/Client/Private/SecretB.luau': 'return {}',
        });

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client'],
            ignoreDirectories: ['src/Server/Private']
        });

        try {
            generateFileAliases();

            const luaurcContent = JSON.parse(fs.readFileSync(path.join(testWorkspacePath, '.luaurc'), 'utf8'));
            assert.ok(!luaurcContent.aliases.SecretA, 'Should ignore file under src/Server/Private');
            assert.ok(luaurcContent.aliases.SecretB, 'Should NOT ignore src/Client/Private — pattern is specific to Server');
        } finally {
            restore();
            cleanupTestFiles(testWorkspacePath, ['src/Server/Private', 'src/Client/Private']);
        }
    });

    test('ignoreDirectories: workspace-relative path pattern works for deeply nested directory', () => {
        createTestFiles(testWorkspacePath, {
            'src/Shared/Deep/Nested/Target/HiddenModule.luau': 'return {}',
            'src/Shared/Deep/Nested/OtherModule.luau': 'return {}'
        });

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Shared'],
            ignoreDirectories: ['src/Shared/Deep/Nested/Target']
        });

        try {
            generateFileAliases();

            const luaurcContent = JSON.parse(fs.readFileSync(path.join(testWorkspacePath, '.luaurc'), 'utf8'));
            assert.ok(!luaurcContent.aliases.HiddenModule, 'Should ignore file inside deeply nested targeted path');
            assert.ok(luaurcContent.aliases.OtherModule, 'Should include sibling outside targeted path');
        } finally {
            restore();
            cleanupTestFiles(testWorkspacePath, ['src/Shared/Deep']);
        }
    });

    test('ignoreDirectories: Windows-style path pattern with backslashes ignores only the specific path', () => {
        createTestFiles(testWorkspacePath, {
            'src/Server/Private/SecretA.luau': 'return {}',
            'src/Client/Private/SecretB.luau': 'return {}'
        });

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server', 'src/Client'],
            ignoreDirectories: ['src\\Server\\Private']
        });

        try {
            generateFileAliases();

            const luaurcContent = JSON.parse(fs.readFileSync(path.join(testWorkspacePath, '.luaurc'), 'utf8'));
            assert.ok(!luaurcContent.aliases.SecretA, 'Should ignore file under src/Server/Private when pattern uses backslashes');
            assert.ok(luaurcContent.aliases.SecretB, 'Should NOT ignore src/Client/Private — pattern is specific to Server');
        } finally {
            restore();
            cleanupTestFiles(testWorkspacePath, ['src/Server/Private', 'src/Client/Private']);
        }
    });

    test('ignoreDirectories: regex with / matches workspace-relative path', () => {
        createTestFiles(testWorkspacePath, {
            'src/Server/Feature/Internal/PrivateImpl.luau': 'return {}',
            'src/Server/Feature/PublicApi.luau': 'return {}'
        });

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server'],
            ignoreDirectories: ['Feature/Internal']
        });

        try {
            generateFileAliases();

            const luaurcContent = JSON.parse(fs.readFileSync(path.join(testWorkspacePath, '.luaurc'), 'utf8'));
            assert.ok(!luaurcContent.aliases.PrivateImpl, 'Should ignore file under Feature/Internal (unanchored path regex)');
            assert.ok(luaurcContent.aliases.PublicApi, 'Should include sibling file not under Internal');
        } finally {
            restore();
            cleanupTestFiles(testWorkspacePath, ['src/Server/Feature']);
        }
    });

    test('ignoreDirectories: anchored name pattern ^_* does not affect non-prefixed dirs', () => {
        createTestFiles(testWorkspacePath, {
            'src/Server/_InternalDir/HiddenFile.luau': 'return {}',
            'src/Server/PublicDir/VisibleFile.luau': 'return {}'
        });

        const restore = mockWorkspaceConfig(testWorkspaceUri, {
            directoriesToScan: ['src/Server'],
            ignoreDirectories: ['^_.*']
        });

        try {
            generateFileAliases();

            const luaurcContent = JSON.parse(fs.readFileSync(path.join(testWorkspacePath, '.luaurc'), 'utf8'));
            assert.ok(!luaurcContent.aliases.HiddenFile, 'Should ignore file under _-prefixed directory');
            assert.ok(luaurcContent.aliases.VisibleFile, 'Should include file under non-prefixed directory');
        } finally {
            restore();
            cleanupTestFiles(testWorkspacePath, ['src/Server/_InternalDir', 'src/Server/PublicDir']);
        }
    });
});
