[package]
name = "raild3x/requireonrails"
description = "An opinionated custom Require library for Roblox"
authors = ["Logan Hunt (Raildex)"]
version = "0.1.5"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[custom]
# The properly capitalized and spaced name of the library
formattedName = "Require On Rails"


[dependencies]
