[package]
name = "empty/empty"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.src.Packages"

[dependencies]

[server-dependencies]
